general.import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
# TERM = "xterm-256color"
TERM = "alacritty"

[window]
# Inner padding 
padding.x = 15
padding.y = 10
# Default width and height of the window
dimensions.columns = 120
dimensions.lines = 40
# Terminal window without buttons
decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 15

[cursor] 
style.shape = "Beam"
vi_mode_style.shape = "Beam"
thickness = 0.3

[keyboard]
# Navigation
bindings = [
  { key = "Left",  mods = "Alt", chars = "\u001b[1;3D" },  # Option+Left → backward-word
  { key = "Right", mods = "Alt", chars = "\u001b[1;3C" },  # Option+Right → forward-word
  { key = "Back",  mods = "Alt", chars = "\u001b\u007f" },   # Option+Backspace → delete word
  { key = "Back",  mods = "Command", chars = "\u0015" },     # Cmd+Backspace → clear entire line
  { key = "Up",    mods = "None", chars = "\u001b[A" },       # Up arrow (command history)
  { key = "Down",  mods = "None", chars = "\u001b[B" }        # Down arrow (command history)
]



