general.import = [
    # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    "~/.config/alacritty/themes/themes/kimbie_dark.toml"
]

[env]
# TERM = "xterm-256color"
TERM = "alacritty"

[window]
# Inner padding 
padding.x = 15
padding.y = 10
# Default width and height of the window
dimensions.columns = 120
dimensions.lines = 40
# Terminal window without buttons
decorations = "Buttonless"

opacity = 0.92
blur = false

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 13.5

[cursor] 
style.shape = "Beam"
vi_mode_style.shape = "Block"
# vi_mode_style.shape = None
thickness = 0.3

[colors.primary]
  # background = "0x1c1c1c"
  foreground = "0xe0e0d0"  # brighter than 0xc5c8c6 colors.text = "CellForeground"

[colors.normal]
black   = "#221a0f"
red     = "#e08a6b"  # slightly brighter
green   = "#a6c47a"  # stronger, more visible green
yellow  = "#f0c28e"  # brighter yellow
blue    = "#749ce0"
magenta = "#d09bea"
cyan    = "#7ed2c8"
white   = "#f0d1a3"

[colors.bright]
black   = "#a4916b"
red     = "#e08a6b"
green   = "#9caf7e"
yellow  = "#f0c28e"
blue    = "#749ce0"
magenta = "#d09bea"
cyan    = "#7ed2c8"
white   = "#fff0c0"  # brighter than #f2cca8

[colors.cursor]
text = '#1E1E2E'
# cursor = '#D9D9D9'
cursor = "#E8C07D"

[keyboard]
# Navigation
bindings = [
  { key = "Left",  mods = "Alt", chars = "\u001b[1;3D" },  # Option+Left → backward-word
  { key = "Right", mods = "Alt", chars = "\u001b[1;3C" },  # Option+Right → forward-word
  { key = "Back",  mods = "Alt", chars = "\u001b\u007f" },   # Option+Backspace → delete word
  { key = "Back",  mods = "Command", chars = "\u0015" },     # Cmd+Backspace → clear entire line
  { key = "Up",    mods = "None", chars = "\u001b[A" },       # Up arrow (command history)
  { key = "Down",  mods = "None", chars = "\u001b[B" }        # Down arrow (command history)
]



